### ISSUE TITLE
!important must die

### ISSUE THREAD

**Issue by MarcoKunz** [codeship/RIG#2]
Das ´!important´ taucht immer wieder auf und eigentlich sollte man in der Lage sein, solche Stellen im CSS einfach mit einer höheren Spezifizität zu lösen.

Zum Beispiel kann man solche Attribute verhindern, indem man eine Klasse irgendeines Elter des Kindselektors nimmt und der Klasse vorangehen lässt oder indem man kombinierte Klassennamen verwendet (z.B. `.klasse1.klasse2`) um vorhergehende Stile zu überschreiben.

Wenn ich mehr Zeit habe, schreib ich das mal um und mache nen Pull Request auf. Sollte auf jeden Fall raus aus dem Framework. Einfach kein guter Stil. Sowas landet bei mir immer in nem shame.scss/shame.less bis ich in der Lage bin, die Abhängigkeit anders aufzulösen.

Aber vielleicht bin ich da auch übervorsichtig bzw. ein Korinthenkacker?! =D

**Comment by Codebryo** [comment]
Thanks for this Marko. The New Version has improved on this kind of stuff.
