### ISSUE TITLE
Gulp errors and exceptions

### ISSUE THREAD

**Issue by miclaus** [codeship/RIG#5]
These are some really weird errors and exceptions which occur very differently. Any hints?

![screen shot 2015-06-17 at 13 05 29](https://cloud.githubusercontent.com/assets/4658706/8205530/c7ed25a6-14f1-11e5-9a9c-f0bcfd0eb5fe.png)
![screen shot 2015-06-17 at 13 05 19](https://cloud.githubusercontent.com/assets/4658706/8205532/c7efa916-14f1-11e5-97d7-52839e718385.png)
![screen shot 2015-06-17 at 11 52 00](https://cloud.githubusercontent.com/assets/4658706/8205531/c7edcc86-14f1-11e5-8e81-97e6fedd60a1.png)

**Comment by Codebryo** [comment]
Hi, this apparently happens when some files are already copied over and somehow gulp won't wait consistently on the cleaning task of removing old files. It can be overcome by doing a 
```
gulp clean
```

before starting with 
```
gulp serve
```
or any other gulp task.
