### ISSUE TITLE
Readme could use more information to explain what this is, exactly.

### ISSUE THREAD

**Issue by itsthatguy** [codeship/RIG#6]

**Comment by Codebryo** [comment]
Hi @itsthatguy thanks for the feedback. A detailed intro with examples and documentation is now available at http://rigframework.com/

I would be very interested in your Feedback :)

Best,
Roman

**Comment by itsthatguy** [comment]
My initial feedback is that this doesn't directly address the raised issue.

It would be especially nice to have a summary explaining what RIG is. Given that a large number of people (possibly most) will find RIG through github, it would be extremely beneficial to give people the context to understand if this is something they would want to use or not. Clicking to another site will create a layer of indirection that could to less "conversion."

But in all seriousness, I don't want to read docs to know if this something like foundation, bootstrap, a grid framework, a css preprocessor, or whatever. I just want to know what it is.

**Comment by itsthatguy** [comment]
Perhaps this is something as simple as a list of features that RIG gives a user.

**Comment by Codebryo** [comment]
Good points. I will take care of this. Thanks for the honest advice.

**Comment by itsthatguy** [comment]
Thanks. :+1: 

As far as the docs, they look great. One thing that confused me for a second was the "Toggle Raw" Link. From a design perspective, It would be super cool to use one of your checkbox switches to indicate its state.
